### PR TITLE
update/112 and 111, bug/121, feature/116: discovery 1 and 2 design updates, and discovery 2 axis name bug, graph updates

### LINKED ISSUE #112: Discovery 1: design updates
Screen Shot 2021-01-20 at 12 16 53 PM

- Graph title: increase line-height to 1.5
- Graph colors: reverse the color scale. Green is good, blue is bad. Increasing gaps are bad so should be blue and vice versa
- Sometimes the font on the graph appears correctly, sometimes it uses system fonts
- Move color scale to the left of the graph instead of on the right. 
- Order of elements (from left to right): 1) axis label; 2) color scale (no need to repeat the axis label for this); 3) axis numbers/increments

### PR DESCRIPTION
**Pull request by alegzandach**
closes #112 #111 #121 #116

### CODE REVIEW

File: themes/base-hugo-theme/assets/js/src/scatterplot/article3.js [hunk 1]
```diff
@@ -279,19 +307,19 @@ var state1 = function(scatterplot) {
...
         formatter: function(value) {
           // remove leading 0's
-          if (value === -0.015) {
-              return value.toString()[0] + value.toString().slice(2)
-          } else if (value === 0.015) {
-              return value.toString().slice(1)
-          } else if (value === 0) {
-              return value
-          }
+          // if (value === -0.015) {
```
Comment (lougroshek) [inline themes/base-hugo-theme/assets/js/src/scatterplot/article3.js:316]: Let's clean some of these comments up before finishing up if we're not going to use them.

**Comment by lougroshek** [comment]
@alegzandach These changes look fine. My only concern is that after resolving merge conflicts there appears to be some sort of regression in the y-axis for the lollipop chart. I think it's probably just a matter of writing some more targeted styling for that element. I'm assuming you'll want to take a look and fix it up yourself so I'll leave as-is. 

Screen Shot 2021-01-26 at 7 13 33 PM
